<?php
 $productos=simplexml_load_file('productos.xml');
 $producto=$productos->addChild('producto');
 $producto->addChild('imagen',$_POST['imagen']);
 $producto->addChild('codigo',$_POST['codigo']);
 $producto->addChild('nombre',$_POST['nombre']);
 $producto->addChild('precio',$_POST['precio']);
 $producto->addChild('categoria',$_POST['categoia']);
 $producto->addChild('descripcion',$_POST['descripcion']);
 $producto->addChild('existencia',$_POST['existencia']);
 file_put_contents('productos.xml',$productos->asXML());
 header('location:index.php?exito=1');
?>